import { User, Wallet, Transaction, Beneficiary } from '../types';

// Mock User Data
export const mockUser: User = {
  id: '1',
  email: 'john.doe@example.com',
  firstName: 'John',
  lastName: 'Doe',
  phone: '+237670123456',
  kycLevel: 2,
  mfaEnabled: true,
  biometricEnabled: true,
  createdAt: new Date().toISOString(),
};

// Mock Wallet Data - XAF as primary currency
export const mockWallets: Wallet[] = [
  {
    id: '1',
    userId: '1',
    currency: 'XAF',
    balance: 2450750,
    status: 'active',
    type: 'current',
    name: 'Current Account',
  },
  {
    id: '2',
    userId: '1',
    currency: 'XAF',
    balance: 1500000,
    status: 'active',
    type: 'savings',
    name: 'Savings Account',
    interestRate: 3.5,
  },
  {
    id: '3',
    userId: '1',
    currency: 'EUR',
    balance: 890.50,
    status: 'active',
    type: 'current',
    name: 'EUR Account',
  },
];

// Mock Transactions - XAF currency
export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'receive',
    amount: 250000,
    currency: 'XAF',
    senderName: 'Alice Mbarga',
    senderEmail: 'alice@example.com',
    status: 'completed',
    method: 'wire',
    fee: 0,
    description: 'Payment for services',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    type: 'send',
    amount: 75000,
    currency: 'XAF',
    recipientName: 'Bob Ndjock',
    recipientEmail: 'bob@example.com',
    status: 'completed',
    method: 'wire',
    fee: 500,
    description: 'Lunch payment',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    type: 'deposit',
    amount: 500000,
    currency: 'XAF',
    status: 'completed',
    method: 'momo_mtn',
    fee: 2500,
    description: 'MTN Mobile Money deposit',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    type: 'withdraw',
    amount: 100000,
    currency: 'XAF',
    status: 'completed',
    method: 'momo_orange',
    fee: 1500,
    description: 'Orange Money withdrawal',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    type: 'send',
    amount: 45000,
    currency: 'XAF',
    recipientName: 'Sarah Eteki',
    recipientEmail: 'sarah@example.com',
    status: 'completed',
    method: 'wire',
    fee: 500,
    description: 'Gift',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    type: 'receive',
    amount: 180000,
    currency: 'XAF',
    senderName: 'Mike Fotso',
    senderEmail: 'mike@example.com',
    status: 'pending',
    method: 'wire',
    fee: 0,
    description: 'Freelance work',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    type: 'send',
    amount: 225000,
    currency: 'XAF',
    recipientName: 'Emma Tchinda',
    recipientEmail: 'emma@example.com',
    status: 'completed',
    method: 'wire',
    fee: 1000,
    description: 'Rent contribution',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    type: 'deposit',
    amount: 400000,
    currency: 'XAF',
    status: 'completed',
    method: 'momo_mtn',
    fee: 2000,
    description: 'MTN Mobile Money deposit',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Beneficiaries
export const mockBeneficiaries: Beneficiary[] = [
  {
    id: '1',
    userId: '1',
    beneficiaryName: 'Alice Smith',
    beneficiaryEmail: 'alice@example.com',
    accountType: 'ewallet',
    nickname: 'Alice',
    isValidated: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    userId: '1',
    beneficiaryName: 'Bob Johnson',
    beneficiaryPhone: '+237123456789',
    accountType: 'momo_mtn',
    nickname: 'Bob MTN',
    isValidated: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    userId: '1',
    beneficiaryName: 'Sarah Williams',
    beneficiaryPhone: '+237555666777',
    accountType: 'momo_orange',
    nickname: 'Sarah OM',
    isValidated: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    userId: '1',
    beneficiaryName: 'Emma Brown',
    accountNumber: '1234567890',
    iban: 'FR7630006000011234567890189',
    bankName: 'BNP Paribas',
    country: 'FR',
    accountType: 'bank',
    nickname: 'Emma Bank',
    isValidated: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    userId: '1',
    beneficiaryName: 'John Doe',
    iban: 'DE89370400440532013000',
    bankName: 'Deutsche Bank',
    country: 'DE',
    accountType: 'bank',
    nickname: 'John DE',
    isValidated: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Linked Accounts
export const mockLinkedAccounts: any[] = [
  {
    id: '1',
    userId: '1',
    provider: 'mtn',
    phoneNumber: '+237670123456',
    accountName: 'John Doe MTN',
    isVerified: true,
    isPrimary: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    userId: '1',
    provider: 'orange',
    phoneNumber: '+237690987654',
    accountName: 'John Doe Orange',
    isVerified: true,
    isPrimary: false,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Helper function to simulate API delay
export const delay = (ms: number = 500) => new Promise(resolve => setTimeout(resolve, ms));

// Generate random transaction ID
export const generateId = () => Math.random().toString(36).substr(2, 9);
