export const countries = [
  { code: 'FR', name: 'France', iban: 'FR', length: 27 },
  { code: 'DE', name: 'Germany', iban: 'DE', length: 22 },
  { code: 'ES', name: 'Spain', iban: 'ES', length: 24 },
  { code: 'IT', name: 'Italy', iban: 'IT', length: 27 },
  { code: 'GB', name: 'United Kingdom', iban: 'GB', length: 22 },
  { code: 'CH', name: 'Switzerland', iban: 'CH', length: 21 },
  { code: 'BE', name: 'Belgium', iban: 'BE', length: 16 },
  { code: 'NL', name: 'Netherlands', iban: 'NL', length: 18 },
  { code: 'AT', name: 'Austria', iban: 'AT', length: 20 },
  { code: 'PT', name: 'Portugal', iban: 'PT', length: 25 },
  { code: 'GR', name: 'Greece', iban: 'GR', length: 27 },
  { code: 'IE', name: 'Ireland', iban: 'IE', length: 22 },
  { code: 'LU', name: 'Luxembourg', iban: 'LU', length: 20 },
  { code: 'PL', name: 'Poland', iban: 'PL', length: 28 },
  { code: 'SE', name: 'Sweden', iban: 'SE', length: 24 },
  { code: 'DK', name: 'Denmark', iban: 'DK', length: 18 },
  { code: 'NO', name: 'Norway', iban: 'NO', length: 15 },
  { code: 'FI', name: 'Finland', iban: 'FI', length: 18 },
  { code: 'CM', name: 'Cameroon', iban: 'CM', length: 27 },
];